[network]
	peer = "tcp_acceptor" # 网络节点名字

[network.processor]
	packet = "ltiv" # 解包的解码器
	message = "protobuf" # 消息类型

[network.tcp_acceptor]
	addr = "127.0.0.1:19001"

[network.ltiv] # 解码配置
	size_length = 2 #包大小字段的长度
	type_length = 1 # 类型字段的长度
	id_length = 2 # 消息id长度
	byte_order = "little" # 字节序