[gxyrpc_server]
	transport = "tcp" # tcp tls unix 
	registery = "etcd" # 支持etcd consul peer
[transport.tcp]
	addr = "localhost:8927"
[transport.unix]
	addr = "/tmp/rpcx.socket"
[registery.etcd]	
	etcd_servers = ["localhost:2379"]
	base_path = "/rpcx_test"
	update_interval = "1m"

	